# Generated by Django 3.2.3 on 2021-05-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'service', 'verbose_name_plural': 'task'},
        ),
        migrations.AlterField(
            model_name='services',
            name='desc',
            field=models.TextField(blank=True, verbose_name='service desc'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='service name'),
        ),
    ]
