# Generated by Django 3.2.3 on 2021-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0004_auto_20210521_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
